SELECT USER
  FROM DUAL;
  

SELECT *
  FROM TBL_MEMBER;
--==>>
/*
2	ÀÌÈ£¼®	010-1111-1111
3	¿ÀÀÌ»è	010-2222-2222
4	ÀÓ¼Ò¹Î	010-3333-3333
*/

INSERT INTO TBL_MEMBER(SID, NAME, TEL)
VALUES(MEMBERSEQ.NEXTVAL, '±è»ó±â', '010-4444-4444');
-- ÇÑÁÙ
INSERT INTO TBL_MEMBER(SID, NAME, TEL) VALUES(MEMBERSEQ.NEXTVAL, '±è»ó±â', '010-4444-4444')
;

SELECT *
  FROM TBL_MEMBER;
COMMIT;

SELECT *
  FROM TBL_MEMBER;
--==>>
/*
2	ÀÌÈ£¼®	010-1111-1111
3	¿ÀÀÌ»è	010-2222-2222
4	ÀÓ¼Ò¹Î	010-3333-3333
8	±è»ó±â	010-4444-4444
9	ÇÑÃæÈñ	010-5555-5555
*/

SELECT *
  FROM TBL_MEMBER;
--==>>
/*
2	ÀÌÈ£¼®	010-1111-1111
3	¿ÀÀÌ»è	010-2222-2222
4	ÀÓ¼Ò¹Î	010-3333-3333
8	±è»ó±â	010-4444-4444
9	ÇÑÃæÈñ	010-5555-5555
10	¹ÚÇö¼ö	010-6666-6666
*/

SELECT *
  FROM TBL_MEMBER;
--==>>
/*
2	ÀÌÈ£¼®	010-1111-1111
3	¿ÀÀÌ»è	010-2222-2222
4	ÀÓ¼Ò¹Î	010-3333-3333
8	±è»ó±â	010-4444-4444
9	ÇÑÃæÈñ	010-5555-5555
10	¹ÚÇö¼ö	010-6666-6666
30	Á¤ÀºÁ¤	010-3030-3030
31	±èÁ¤¿ë	010-3131-3131
*/

SELECT SID, NAME, TEL
  FROM TBL_MEMBER
ORDER BY SID;

SELECT SID, NAME, TEL  FROM TBL_MEMBER ORDER BY SID
;
----------------------------------------------------------------

SELECT *
  FROM TBL_SCORE;
  
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT)
VALUES(SCORESEQ.NEXTVAL, '±è¶¯¶¯', 50, 80, 76);
--==>> 1 Çà ÀÌ(°¡) »ðÀÔµÇ¾ú½À´Ï´Ù.
INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES(SCORESEQ.NEXTVAL, '±è¶¯¶¯', 50, 80, 76)
;

--¡Û ÀüÃ¼ ÀÎ¿ø
SELECT COUNT(*) AS COUNT
  FROM TBL_SCORE;
--
SELECT COUNT(*) AS COUNT  FROM TBL_SCORE
;

--¡Û ÀüÃ¼ Ãâ·Â
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, (KOR+ENG+MAT)/3 AS AVG
  FROM TBL_SCORE
ORDER BY SID;
--
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, (KOR+ENG+MAT)/3 AS AVG  FROM TBL_SCORE ORDER BY SID
;

SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, (KOR+ENG+MAT)/3 AS AVG
  FROM TBL_SCORE
 WHERE NAME = '¹ÚÇö¼ö';
--
SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, (KOR+ENG+MAT)/3 AS AVG  FROM TBL_SCORE WHERE NAME = '¹ÚÇö¼ö'
;

SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) AS TOT, (KOR+ENG+MAT)/3 AS AVG
  FROM TBL_SCORE
 WHERE SID = 1;
   
   
SELECT * FROM
( SELECT SID, NAME, KOR, ENG, MAT, (KOR + ENG + MAT) AS TOT
, (KOR + ENG + MAT)/3 AS AVG
, RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK
 FROM TBL_SCORE )
 WHERE SID = 1;

SELECT *
FROM
(
    SELECT SID, NAME, KOR, ENG, MAT
         , (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT)/3 AS AVG
         , RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK
      FROM TBL_SCORE
);

SELECT SID, NAME, KOR, ENG, MAT
     , (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT)/3 AS AVG
     , RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK
  FROM TBL_SCORE
ORDER BY SID;
--
SELECT SID, NAME, KOR, ENG, MAT, (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT)/3 AS AVG, RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK FROM TBL_SCORE ORDER BY SID
;

SELECT SID, NAME, KOR, ENG, MAT
     , (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT)/3 AS AVG
     , RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK
  FROM TBL_SCORE
 WHERE NAME = '¹ÚÇö¼ö';
--
SELECT SID, NAME, KOR, ENG, MAT, (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT)/3 AS AVG, RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK FROM TBL_SCORE WHERE NAME = '¹ÚÇö¼ö'
;

SELECT SID, NAME, KOR, ENG, MAT
     , (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT)/3 AS AVG
     , RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK
  FROM TBL_SCORE
 WHERE SID = 1;
--
SELECT SID, NAME, KOR, ENG, MAT, (KOR + ENG + MAT) AS TOT, (KOR + ENG + MAT)/3 AS AVG, RANK() OVER(ORDER BY (KOR + ENG + MAT) DESC) AS RANK FROM TBL_SCORE WHERE SID = 1
;

UPDATE TBL_SCORE
   SET NAME = 'ÀÌ¶¯¶¯', KOR=50, ENG=80, MAT=70
 WHERE SID = 1;
--
UPDATE TBL_SCORE SET NAME = 'ÀÌ¶¯¶¯', KOR=50, ENG=80, MAT=70 WHERE SID = 1
;

SELECT *
  FROM TBL_SCORE;

ROLLBACK;

DELETE
  FROM TBL_SCORE
 WHERE SID = 1;
--
DELETE FROM TBL_SCORE WHERE SID = 1
;

SELECT * FROM TBL_SCORE;





